name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ vars.NODE_ENV }}
    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      DB_HOST: ${{ vars.DB_HOST }}
      SESSION_SECRET: ${{ vars.SESSION_SECRET }}
      NODE_ENV: ${{ vars.NODE_ENV }}
      ADICIONAR_DADOS: ${{ vars.ADICIONAR_DADOS }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Print name
      run: echo $NODE_ENV
    - run: npm ci
    - run: npm install
    - run: npm run build --if-present
    - run: npm start
